### ISSUE TITLE
Question: Windows Opened Feature enabled by default for TZE200_hue3yfsn?

### ISSUE THREAD

**Issue by iDazai** [jacekk015/zha_quirks#27]
Hey, this is only a question, is the sensor to detect if a windows is open enabled by default? In the original ZHA there was a temperature slider to say when it should detect if a window might be open. If it's enabled by default, how does it work? At a certain temperature or like how the manufacturer implemented it (5 °C dropoff in 5 minutes)?

The device is use is ("_TZE200_hue3yfsn", "TS0601") # Zonnsmart TV02-ZG

**Comment by jacekk015** [comment]
There were few tests of that function for different TRV's and most users agreed that this function works best if you put a TRV in the freezer. I did that myself, because opened window couldn't trigger that function. Fridge didn't trigger that either.
I was just curious if that was even implemented.

You have the TRV - check how Chinese engineers made it in the firmware. If you just open a window you can observe the behavior.
I'm almost sure nothing will happen. Temp drop is too low or too small, or both.
