### ISSUE TITLE
MOES _TZE204_aoclfnxz TS060 cannot set target temp to 0.5 degrees steps

### ISSUE THREAD

**Issue by glcos** [jacekk015/zha_quirks#29]
Using ts0601_thermostat_avatto.py
I cannot set the target temperature to 0.5 degrees steps, example if I set 22.5 the thermostat goes to 23.0, if I set 21.5 on the thermostat I read 21.0 on HA entity.
Everything else working fine, including time sync.

**Comment by jacekk015** [comment]
Debug logs are needed from doing that action. After temp change you need to log still a few minutes best 5 minimum.
https://github.com/jacekk015/zha_quirks#in-case-of-errors-or-to-support-new-function

Some time the reason was that when you've changed temp with 0.5 resolutions Device returned rounded response.
Only logs can show what's going on.

**Comment by glcos** [comment]
@jacekk015 
> Some time the reason was that when you've changed temp with 0.5 resolutions Device returned rounded response.

You are right, this is exactely what happens, I have checked the logs. The device always returns integer temperature setpoint, despite what is being sent by zigbee.

Do you know if all zigbee Tuya clones are behaving like this? Does the real AVATTO thermostat has this limitation too?

**Comment by jacekk015** [comment]
From what I know, that's you and one device earlier. Maybe it's the same model. Don't remember exactly.
