### ISSUE TITLE
AVATTO ZWT198 - It's possible to add battery information?

### ISSUE THREAD

**Issue by Danieldiazi** [jacekk015/zha_quirks#52]
Hi

I've used avatto zwt198 quirk file and it works ok.  Thanks!

This device is powered with 3 batteries.

Into device configuration I don't see any information about battery status, and I have "Unknown" value for this information
![imagen](https://github.com/jacekk015/zha_quirks/assets/3638478/282b20fa-5f76-4707-910d-b58348df5eb9)

I wonder if it's possible to add this battery information.

I can see attribute information at TuyaPowerConfigurationCluster, therefore, it seems the information about battery is available, but I don't know how to modify this quirk file in order to add this feature. 

![imagen](https://github.com/jacekk015/zha_quirks/assets/3638478/c5991778-3620-423f-9fe4-6e5abcc9c663)

Moreover, when I see TuyaPowerConfigurationCluster  attributes,  like battery2 percentage remaining, the value is None. If it doesn't show that information, even if the quirk is modified, won't it work?

![imagen](https://github.com/jacekk015/zha_quirks/assets/3638478/c66da526-5019-4d86-8ff5-da76ad2d2dfd)

**Comment by jacekk015** [comment]
Because none of the user knows on which attribute the battery level is.
So you would need to debug it.
Firstly there's need to check on the app+gateway setup if an app gets a battery level. There are devices that doesn't report it at all through Zigbee or only report Full/Empty
Enable DEBUG level logging according to:
https://github.com/jacekk015/zha_quirks?tab=readme-ov-file#in-case-of-errors-or-to-support-new-function

Second - when paired with ZHA remove temporary battery and put it back.
That way device sends all data through Zigbee to HA.
Post here a FULL log
Then we can try to search for something that looks like that.
Above play, with ZHA, could be repeat again with almost empty set of batteries, so we could track the difference.

**Comment by Danieldiazi** [comment]
> Because none of the user knows on which attribute the battery level is. So you would need to debug it. Firstly there's need to check on the app+gateway setup if an app gets a battery level. There are devices that doesn't report it at all through Zigbee or only report Full/Empty Enable DEBUG level logging according to: https://github.com/jacekk015/zha_quirks?tab=readme-ov-file#in-case-of-errors-or-to-support-new-function
> 
> Second - when paired with ZHA remove temporary battery and put it back. That way device sends all data through Zigbee to HA. Post here a FULL log Then we can try to search for something that looks like that. Above play, with ZHA, could be repeat again with almost empty set of batteries, so we could track the difference.

HI, thanks for your support. I've attached my zigbee log file, but maybe it only contains a few minutes of info and  maybe I need to get logs more time?
[zigbee2.log](https://github.com/jacekk015/zha_quirks/files/14588917/zigbee2.log)

If this file is enough, I'll find a almost empty set of batteries and repeat the test.
.
