### ISSUE TITLE
Support for _TZE204_rtrmfadk

### ISSUE THREAD

**Issue by flatpackfan** [jacekk015/zha_quirks#62]
Would be great if you'd be able to support the `TS0601_TZE204_rtrmfadk` thermostat. There seems to be some data on this device [here](https://github.com/Koenkk/zigbee2mqtt/issues/20189) and [here](https://github.com/sprut/Hub/issues/3533). Happy to provide any additional diagnostics data you need.

[Aliexpress](https://www.aliexpress.com/item/1005005581681496.html?spm=a2g0o.order_list.order_list_main.5.f44c1802DzzBKm)

**Comment by jacekk015** [comment]
Similar is supported here

ts0601_trv_rtitek.py

Debug data needed

**Comment by jacekk015** [comment]
https://github.com/jacekk015/zha_quirks?tab=readme-ov-file#in-case-of-errors-or-to-support-new-function

You need to download ts0601_trv_rtitek.py and add your model do the list.
Restart HA
Remove and Pair like a brand new
Test

**Comment by jacekk015** [comment]
- Current/target temperature sometimes gets reported as 100c
Logs needed
Rtitek has added filter for some temp values, because that stupid TRV was sending occasionally strange values.

- Controls: switch - not sure what this should do or if it works (child lock)
Child Lock

- Sensors: binary input - not sure what this should do or if it works
From the code
```
class RtiWindowDetection(LocalDataCluster, BinaryInput):
```

- Sensors: HVAC action - not sure what this should do or if it works
```
```

- Diagnostics: battery - reported as unknown
- Diagnostics: timestamp - reported as unknown

**Comment by tco99ttocs** [comment]
i got a similar trv, but its shown as _TZE204_ltwbm23f"! I added the model to "ts0601_trv_rtitek.py" and i can see all the setting, but if i try to change something, nothing happens!

**Comment by pr8x** [comment]
@jacekk015 I successfully paired my device by manually adding the signature to ts0601_trv_rtitek.py. Seems to work for the most part, but system modes appear to be broken. After I turn the device off it's stuck in "Idle" mode and I cannot turn it back on again (without manually adjusting the valve). 

![image](https://github.com/user-attachments/assets/a05b144a-df81-4aec-8569-411e5e82ec98)

Attached some debug logs: 
[hass_log_debug_zha.txt](https://github.com/user-attachments/files/18229867/hass_log_debug_zha.txt)
